# Generated by Django 4.0.3 on 2022-05-21 18:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoppers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SuitablityRaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ParamRaster',
            fields=[
                ('type', models.CharField(max_length=255)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('suitablity_raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suitablityraster')),
            ],
        ),
        migrations.CreateModel(
            name='GraphImg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('graph', models.ImageField(upload_to='')),
                ('suitablity_raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suitablityraster')),
            ],
        ),
    ]
