# Generated by Django 4.0.3 on 2022-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphimg',
            name='graph',
            field=models.ImageField(upload_to='graphs/'),
        ),
    ]
